'use client'
import './globals.css'
import { Londrina_Solid, Darumadrop_One } from 'next/font/google'
import { AnimatePresence } from 'framer-motion'

const Lod = Londrina_Solid({ weight: ['100', '300', '400', '900'], subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${Lod.className} relative`}>{children}</body>
    </html>
  )
}
