'use client'
import './globals.css'
import { Londrina_Solid } from 'next/font/google'
import { createContext, useEffect, useState, useRef } from 'react'

const Lod = Londrina_Solid({ weight: ['100', '300', '400', '900'], subsets: ['latin'] })

export const metadata = {
  title: 'ERU',
  description: 'Generated by create next app',
}

export const ThemeContext = createContext<any>([] as any)

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [mode, setMode] = useState(true)
  const modeRef = useRef<HTMLBodyElement>(null)
  useEffect(() => {
    setTimeout(() => {
      if (mode == true) {
        modeRef.current?.classList.add('text-secondary', 'bg-darkMode')
        modeRef.current?.classList.remove('text-teritary', 'bg-lightMode')
      } else if (mode == false) {
        modeRef.current?.classList.add('text-teritary', 'bg-lightMode')
        modeRef.current?.classList.remove('text-secondary', 'bg-darkMode')
      }
    }, 750)
    console.log(mode)
  })
  return (
    <html lang="en">
      <body ref={modeRef} suppressHydrationWarning={true} className={`${Lod.className} mx-auto lg:w-[40vw] sm:px-4  `}>
        <ThemeContext.Provider value={[mode, setMode]}>{children}</ThemeContext.Provider>
      </body>
    </html>
  )
}
