import './globals.css'
import { Londrina_Solid } from 'next/font/google'

const Lod = Londrina_Solid({ weight: ['100', '300', '400', '900'], subsets: ['latin'] })

export const metadata = {
  title: 'ERU',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${Lod.className} `}>
        <div className="bg-white ">{children}</div>
      </body>
    </html>
  )
}
